name: Enforce License Compliance

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
        fetch-depth: 0

     - name: Check for copyleft licenses
       uses: getsentry/copyleft-license-checker@main

